<?php

namespace AppBundle\Repository;

/**
 * ServicesCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicesCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
