<?php

namespace AppBundle\Repository;

/**
 * SurferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurferRepository extends \Doctrine\ORM\EntityRepository
{
}
