<?php

namespace AppBundle\Repository;

/**
 * TraineeShipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraineeShipRepository extends \Doctrine\ORM\EntityRepository
{
}
